# -*- coding: utf-8 -*-
"""analysis_and_tdd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpZUXSJzruxTb34GM_f5ERTznS8OaJVl
"""

import os
import json
import re
from collections import defaultdict, Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from utils import to_commit_df, classify_commits, is_test_file, is_prod_file


# Helpers

def ensure_dirs():
    os.makedirs("analysis", exist_ok=True)
    os.makedirs("analysis/figures", exist_ok=True)
    os.makedirs("analysis/tables", exist_ok=True)


def norm_path(p: str) -> str:
    return (p or "").replace("\\", "/").strip()


def get_file_path(mf: dict) -> str:
    # Prefer full paths if present
    return norm_path(mf.get("new_path") or mf.get("old_path") or mf.get("filename") or "")


def is_java(p: str) -> bool:
    return norm_path(p).lower().endswith(".java")


def safe_div(a, b):
    return None if b == 0 else a / b


def repo_df_from_json(repo_json: dict) -> pd.DataFrame:
    df = to_commit_df(repo_json)

    stats = classify_commits(df)
    df["test_file_mods"] = stats["test_counts"]
    df["code_file_mods"] = stats["code_counts"]
    df["unknown_java_file_mods"] = stats["unknown_java_counts"]
    df["commit_type"] = stats["commit_types"]

    # Standard analysis slice: main branch, non-merge, has java changes
    df_main = df[(df["on_main"]) & (~df["is_merge"]) & (df["commit_type"] != "none")].copy()
    df_main = df_main.sort_values("dt")
    return df, df_main



# Metric 1: Commit-type proportions

def commit_type_metrics(df_main: pd.DataFrame) -> dict:
    counts = df_main["commit_type"].value_counts()
    total = int(counts.sum())
    return {
        "nonmerge_main_commits": total,
        "code_only_commits": int(counts.get("code_only", 0)),
        "test_only_commits": int(counts.get("test_only", 0)),
        "mixed_commits": int(counts.get("mixed", 0)),
        "pct_code_only": safe_div(float(counts.get("code_only", 0)), total),
        "pct_test_only": safe_div(float(counts.get("test_only", 0)), total),
        "pct_mixed": safe_div(float(counts.get("mixed", 0)), total),
    }



# Metric 2: Co-evolution probabilities

def coevolution_probs(df_main: pd.DataFrame) -> dict:
    mixed = int((df_main["commit_type"] == "mixed").sum())
    code_only = int((df_main["commit_type"] == "code_only").sum())
    test_only = int((df_main["commit_type"] == "test_only").sum())

    # P(test change | code change)
    p_test_given_code = safe_div(mixed, (mixed + code_only))
    # P(code change | test change)
    p_code_given_test = safe_div(mixed, (mixed + test_only))

    return {
        "p_test_change_given_code_change": p_test_given_code,
        "p_code_change_given_test_change": p_code_given_test,
    }



# Metric 3: Sequence-based "test-first tendency"

def sequence_rate_by_author(df_main: pd.DataFrame, window_commits: int = 3) -> dict:
    """
    For each author: for every test_only commit, check if within next N commits
    by same author there is a code_only or mixed commit.
    """
    total_test_only = 0
    followed = 0

    for author, g in df_main.groupby("author"):
        g = g.sort_values("dt").reset_index(drop=True)
        for i, row in g.iterrows():
            if row["commit_type"] != "test_only":
                continue
            total_test_only += 1
            future = g.loc[i + 1 : i + window_commits, "commit_type"].tolist()
            if any(ct in ("code_only", "mixed") for ct in future):
                followed += 1

    return {
        "sequence_window_commits": window_commits,
        "test_only_followed_by_code_or_mixed": followed,
        "sequence_rate": safe_div(followed, total_test_only),
    }


def sequence_rate_time_window(df_main: pd.DataFrame, hours: int = 72) -> dict:
    """
    Alternative: for each test_only commit, check if same author makes code_only/mixed
    within X hours.
    """
    total_test_only = 0
    followed = 0
    cutoff = pd.Timedelta(hours=hours)

    for author, g in df_main.groupby("author"):
        g = g.sort_values("dt").reset_index(drop=True)
        for i, row in g.iterrows():
            if row["commit_type"] != "test_only":
                continue
            total_test_only += 1
            t0 = row["dt"]
            if pd.isna(t0):
                continue
            # look ahead until time window exceeded
            j = i + 1
            ok = False
            while j < len(g):
                tj = g.loc[j, "dt"]
                if pd.isna(tj) or (tj - t0) > cutoff:
                    break
                if g.loc[j, "commit_type"] in ("code_only", "mixed"):
                    ok = True
                    break
                j += 1
            if ok:
                followed += 1

    return {
        "sequence_window_hours": hours,
        "test_only_followed_by_code_or_mixed_within_window": followed,
        "sequence_rate_time_window": safe_div(followed, total_test_only),
    }



# Metric 4: File intro order via lightweight traceability

def candidate_test_paths_for_prod(prod_path: str) -> list[str]:
    """
    Generate candidate test paths for a production file using filename morphisms.
    Works even if projects use different roots; relies mostly on folder replacement.
    """
    p = norm_path(prod_path)
    if not p.lower().endswith(".java"):
        return []

    # Split dirname and basename
    parts = p.split("/")
    base = parts[-1]
    cls = base[:-5]  # Foo from Foo.java
    dirpath = "/".join(parts[:-1])

    # Common test roots we can try (project-agnostic)
    # We'll map by replacing common source roots with test roots, *if present*.
    src_roots = ["src/main/java", "src/java", "src", "main", "lib"]
    test_roots = ["src/test/java", "src/test", "test", "tests", "test/unit", "test/integration"]

    candidates = []

    # Directory-mapped candidates
    for sroot in src_roots:
        if dirpath.lower().startswith(sroot):
            rel = dirpath[len(sroot):].lstrip("/")
            for troot in test_roots:
                tdir = f"{troot}/{rel}".rstrip("/")
                candidates += [
                    f"{tdir}/{cls}Test.java",
                    f"{tdir}/Test{cls}.java",
                    f"{tdir}/{cls}Tests.java",
                ]

    # Same-dir filename-only fallback (rare but cheap)
    candidates += [
        f"{dirpath}/{cls}Test.java",
        f"{dirpath}/Test{cls}.java",
        f"{dirpath}/{cls}Tests.java",
    ]

    # De-dup preserve order
    seen = set()
    out = []
    for c in candidates:
        c = norm_path(c)
        if c and c not in seen:
            seen.add(c)
            out.append(c)
    return out


def compute_first_seen_file_times(df_main: pd.DataFrame) -> tuple[dict, dict]:
    """
    Returns:
      first_prod: prod_path -> first datetime
      first_test: test_path -> first datetime
    Uses utils.is_test_file / is_prod_file where possible.
    """
    first_prod = {}
    first_test = {}

    for _, row in df_main.sort_values("dt").iterrows():
        dt = row["dt"]
        if pd.isna(dt):
            continue
        for mf in (row["modified_files"] or []):
            path = get_file_path(mf)
            if not path or not is_java(path):
                continue

            # classify using existing heuristics
            if is_test_file(path):
                first_test.setdefault(path, dt)
            elif is_prod_file(path):
                first_prod.setdefault(path, dt)
            else:
                # unknown java: treat as prod for intro-order purposes (consistent with your classify_commits)
                first_prod.setdefault(path, dt)

    return first_prod, first_test


def file_intro_order_metrics(df_main: pd.DataFrame) -> dict:
    """
    For each production file, try to find a candidate test file.
    Compare first-seen timestamps to classify as test_first/parallel/later/no_test_observed.
    """
    first_prod, first_test = compute_first_seen_file_times(df_main)

    results = Counter()
    matched = 0

    for prod_path, prod_dt in first_prod.items():
        candidates = candidate_test_paths_for_prod(prod_path)
        existing_times = [first_test[c] for c in candidates if c in first_test]

        if not existing_times:
            results["no_test_observed"] += 1
            continue

        matched += 1
        test_dt = min(existing_times)
        if test_dt < prod_dt:
            results["test_first"] += 1
        elif test_dt == prod_dt:
            results["test_parallel"] += 1
        else:
            results["test_later"] += 1

    total_prod = sum(results.values())
    coverage = safe_div(matched, total_prod)  # share of prod files with a matched candidate test

    # percentages
    def pct(k):
        return safe_div(results.get(k, 0), total_prod)

    return {
        "prod_files_total_for_intro": total_prod,
        "traceability_match_coverage": coverage,
        "intro_test_first": int(results.get("test_first", 0)),
        "intro_test_parallel": int(results.get("test_parallel", 0)),
        "intro_test_later": int(results.get("test_later", 0)),
        "intro_no_test_observed": int(results.get("no_test_observed", 0)),
        "pct_intro_test_first": pct("test_first"),
        "pct_intro_test_parallel": pct("test_parallel"),
        "pct_intro_test_later": pct("test_later"),
        "pct_intro_no_test_observed": pct("no_test_observed"),
    }



# Metric 5: Commit size stats (non-merge main)

def commit_size_stats(df_main: pd.DataFrame) -> dict:
    sizes = df_main["num_lines_changed"].dropna()
    return {
        "median_lines_changed": float(sizes.median()) if len(sizes) else None,
        "p95_lines_changed": float(sizes.quantile(0.95)) if len(sizes) else None,
    }


def commit_size_by_type(df_main: pd.DataFrame) -> dict:
    out = {}
    for ct in ["code_only", "test_only", "mixed"]:
        sizes = df_main.loc[df_main["commit_type"] == ct, "num_lines_changed"].dropna()
        out[f"{ct}_median_lines"] = float(sizes.median()) if len(sizes) else None
        out[f"{ct}_p95_lines"] = float(sizes.quantile(0.95)) if len(sizes) else None
        out[f"{ct}_count_sizes"] = int(len(sizes))
    return out



# Time-sliced stats (per year)

def per_year_commit_type_table(df_main: pd.DataFrame) -> pd.DataFrame:
    return (
        df_main.groupby(["year", "commit_type"])
        .size()
        .unstack(fill_value=0)
        .reset_index()
        .sort_values("year")
    )



# Plotting

def plot_commit_type_proportions(summary_df: pd.DataFrame, outpath: str):
    repos = summary_df["repo"].tolist()
    x = np.arange(len(repos))
    w = 0.25

    plt.figure()
    plt.bar(x - w, summary_df["pct_code_only"], width=w, label="code_only")
    plt.bar(x, summary_df["pct_test_only"], width=w, label="test_only")
    plt.bar(x + w, summary_df["pct_mixed"], width=w, label="mixed")
    plt.xticks(x, repos, rotation=30, ha="right")
    plt.ylabel("proportion (main, non-merge)")
    plt.title("Commit type proportions by repository")
    plt.legend()
    plt.tight_layout()
    plt.savefig(outpath, dpi=200)
    plt.close()


def plot_sequence_rates(summary_df: pd.DataFrame, col: str, title: str, outpath: str):
    df = summary_df.copy()
    df = df.dropna(subset=[col])
    plt.figure()
    plt.bar(df["repo"], df[col])
    plt.xticks(rotation=30, ha="right")
    plt.ylabel("rate")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(outpath, dpi=200)
    plt.close()


def plot_intro_order(summary_df: pd.DataFrame, outpath: str):
    repos = summary_df["repo"].tolist()
    x = np.arange(len(repos))
    w = 0.2

    plt.figure()
    plt.bar(x - 1.5*w, summary_df["pct_intro_test_first"], width=w, label="test_first")
    plt.bar(x - 0.5*w, summary_df["pct_intro_test_parallel"], width=w, label="test_parallel")
    plt.bar(x + 0.5*w, summary_df["pct_intro_test_later"], width=w, label="test_later")
    plt.bar(x + 1.5*w, summary_df["pct_intro_no_test_observed"], width=w, label="no_test_observed")

    plt.xticks(x, repos, rotation=30, ha="right")
    plt.ylabel("proportion of prod files")
    plt.title("File introduction order (lightweight traceability)")
    plt.legend()
    plt.tight_layout()
    plt.savefig(outpath, dpi=200)
    plt.close()


def plot_commit_size(summary_df: pd.DataFrame, outpath: str):
    repos = summary_df["repo"].tolist()
    x = np.arange(len(repos))
    w = 0.35

    plt.figure()
    plt.bar(x - w/2, summary_df["median_lines_changed"], width=w, label="median")
    plt.bar(x + w/2, summary_df["p95_lines_changed"], width=w, label="95th percentile")
    plt.xticks(x, repos, rotation=30, ha="right")
    plt.ylabel("lines changed")
    plt.title("Commit size (main, non-merge): median vs 95th percentile")
    plt.legend()
    plt.tight_layout()
    plt.savefig(outpath, dpi=200)
    plt.close()



# Main runner

def run_all(data_dir="data"):
    ensure_dirs()

    rows = []
    per_repo_year_tables = {}

    for file in sorted(os.listdir(data_dir)):
        if not file.endswith(".json"):
            continue

        path = os.path.join(data_dir, file)
        with open(path, "r", encoding="utf-8") as f:
            repo_json = json.load(f)

        df_all, df_main = repo_df_from_json(repo_json)

        repo = df_all["repo"].iloc[0] if len(df_all) else repo_json.get("name", file.replace(".json", ""))

        m = {"repo": repo}

        # 1) commit types
        m.update(commit_type_metrics(df_main))

        # 2) co-evolution probabilities
        m.update(coevolution_probs(df_main))

        # 3) sequence metrics (two variants)
        m.update(sequence_rate_by_author(df_main, window_commits=3))
        m.update(sequence_rate_time_window(df_main, hours=72))

        # 4) file intro order (lightweight traceability)
        m.update(file_intro_order_metrics(df_main))

        # 5) commit size stats
        m.update(commit_size_stats(df_main))
        m.update(commit_size_by_type(df_main))

        rows.append(m)

        # optional per-year table for this repo
        per_repo_year_tables[repo] = per_year_commit_type_table(df_main)

        print(f"done: {repo} | commits(main, non-merge): {m['nonmerge_main_commits']}")

    summary = pd.DataFrame(rows).sort_values("repo")

    # Save tables
    summary.to_csv("analysis/tables/summary_tdd_evidence.csv", index=False)
    for repo, tdf in per_repo_year_tables.items():
        safe_repo = re.sub(r"[^A-Za-z0-9_.-]+", "_", repo)
        tdf.to_csv(f"analysis/tables/{safe_repo}_commit_types_per_year.csv", index=False)

    # Plots (cross-repo comparisons)
    plot_commit_type_proportions(summary, "analysis/figures/commit_type_proportions.png")
    plot_sequence_rates(
        summary,
        "sequence_rate",
        "Test-only commits followed soon by code/mixed (next 3 commits, same author)",
        "analysis/figures/sequence_rate_next3.png",
    )
    plot_sequence_rates(
        summary,
        "sequence_rate_time_window",
        "Test-only commits followed by code/mixed within 72h (same author)",
        "analysis/figures/sequence_rate_72h.png",
    )
    plot_sequence_rates(
        summary,
        "p_test_change_given_code_change",
        "P(test change | code change) by repository",
        "analysis/figures/p_test_given_code.png",
    )
    plot_intro_order(summary, "analysis/figures/file_intro_order.png")
    plot_commit_size(summary, "analysis/figures/commit_size_median_p95.png")

    print("saved:")
    print(" - analysis/tables/summary_tdd_evidence.csv")
    print(" - analysis/figures/*.png")
    print(" - analysis/tables/*_commit_types_per_year.csv")
    return summary


if __name__ == "__main__":
    # If your mined json folder has a different name, change it here.
    run_all(data_dir="data")